[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools >= 64"]

[project]
authors = [
    {name = "Simone Chiarella", email = "simonechiarella99@gmail.com"},
]
dependencies = [
    "biopython",
    "matplotlib",
    "numpy",
    "pandas",
    "rcsbsearchapi",
    "rich",
    "scipy",
    "seaborn",
    "torch",
    "transformers",
]
description = "A pipeline for the analisys of protein networks through BERT self-attention"
dynamic = ["version"]
license = {file = "LICENSE"}
name = "ProtACon"
readme = "README.md"
requires-python = ">= 3.10"

[project.optional-dependencies]
test = [
    "mypy==1.11.2",
    "pandas-stubs=2.2.2.240909",
    "pytest==7.4.4",
    "pytest-bdd==1.0.6",
    "pytest-pep8==7.0.0",
]

[project.scripts]
ProtACon = "ProtACon.__main__:main"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
testpaths = ["tests"]